### ISSUE TITLE
Installation of frappe-manager fails due to AttributeError in pkgutil module

### ISSUE THREAD

**Issue by rehan-vastites** [rtCamp/Frappe-Manager#210]
I encountered an error while trying to install the frappe-manager package using pip. The installation process fails during the metadata generation step for the cloudflare package. The error seems to be related to the pkgutil module, which does not have the attribute `ImpImporter`.

pip install frappe-manager

pip --version
pip 24.1 from /home/rehan/.local/lib/python3.12/site-packages/pip (python 3.12)

![image](https://github.com/rtCamp/Frappe-Manager/assets/163822052/5adb2fab-5b23-4611-8dfc-d0a0719abc27)

**Comment by Xieyt** [comment]
Please let me know this:
- os
- os version
- system's architecture

**Comment by rehan-vastites** [comment]
> Please let me know this:
> 
> * os
> * os version
> * system's architecture

![image](https://github.com/rtCamp/Frappe-Manager/assets/163822052/8d1230ab-6a78-4e7a-84c7-e74a09ef6dbd)

**Comment by iamimmanuelraj** [comment]
I tried to replicate this. And it works for me.

Can you try this

`sudo apt install python-is-python3 python3-dev pipx` 

Then 

`pipx install frappe-manager`

**Comment by nainikasingh** [comment]
You can downgrade your Python version to 3.11 or lower, or you can apply a patch to the affected package. As the error you're encountering is due to a change in Python 3.12 where the 'ImpImporter' class was removed from the 'pkgutil' module. 
If you prefer to use Python 3.12, you'll need to wait for the package maintainers to update the affected packages to be compatible with Python 3.12 or manually patch the package yourself.
